---
AWSTemplateFormatVersion: 2010-09-09

Parameters:
  S3BucketName:
    Type: String
  S3AlternativeDomainName:
    Type: String
  AcmCertificateArn:
    Type: String

Resources:
  DomainBucketRootPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3BucketName
      PolicyDocument:
        Statement:
          - Action:
              - s3:GetObject
            Effect: Allow
            Resource:
              - !Sub arn:aws:s3:::${S3BucketName}/*
            Principal: "*"
  DomainBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3BucketName
      WebsiteConfiguration:
        IndexDocument: INT.html
        ErrorDocument: INT.html
  DomainBucketDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: http-only
            DomainName: !Sub ${S3BucketName}.s3-website-${AWS::Region}.amazonaws.com
            Id: origin
        DefaultCacheBehavior:
          ForwardedValues:
            QueryString: false
            Headers:
              - CloudFront-Viewer-Country
          TargetOriginId: origin
          ViewerProtocolPolicy: redirect-to-https
          LambdaFunctionAssociations:
            - EventType: origin-request
              LambdaFunctionARN: !Ref VersionedLambdaRenderFunction
        Aliases:
          - !Sub ${S3AlternativeDomainName}
        ViewerCertificate:
          AcmCertificateArn: !Ref AcmCertificateArn
          SslSupportMethod: sni-only
        Enabled: true
  LambdaBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
                - edgelambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - !Ref LambdaBuildRoleBucketPolicy
  LambdaBuildRoleBucketPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - s3:PutObject
            Resource: !Sub arn:aws:s3:::${S3BucketName}/*
  LambdaBuildFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code: functions/build
      Handler: index.handler
      MemorySize: 128
      Role: !GetAtt LambdaBuildRole.Arn
      Runtime: nodejs20.x
      Timeout: 300
      Environment:
        Variables:
          NODE_ENV: production
          S3_BUCKET: !Ref S3BucketName
  LambdaBuildEventPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt LambdaBuildFunction.Arn
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt LambdaBuildEventRule.Arn
  LambdaBuildEventRule:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: cron(0 0 * * ? *)
      Targets:
        - Arn: !GetAtt LambdaBuildFunction.Arn
          Id: build-event-rule
  LambdaRenderRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
                - edgelambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
  LambdaRenderFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code: functions/render
      Handler: index.handler
      MemorySize: 128
      Role: !GetAtt LambdaRenderRole.Arn
      Runtime: nodejs20.x
      Timeout: 5
  VersionedLambdaRenderFunction:
    Type: AWS::Lambda::Version
    Properties:
      FunctionName: !Ref LambdaRenderFunction

Outputs:
  DistributionURL:
    Description: The cloudfront distribution URL
    Value: !GetAtt DomainBucketDistribution.DomainName
