#!/bin/sh

set -e

if [ -z "$1" ] ; then
  echo 'Expected stack as argument'
  exit 1
fi

aws cloudformation create-stack \
  --stack-name frontpage-today-$1 \
  --stack-region us-east-1 \
  --template-body file://stack.yml \
  --parameters file://parameters/$1.json \
  --timeout-in-minutes 10
