#!/usr/bin/env node

import { handler } from "../functions/build/index.js";

const event = {};
const context = {};
const callback = () => {};

handler(event, context, callback).catch((error) => {
  console.error(error);
});
