#!/usr/bin/env node

const build = require("../functions/build");

const event = {};
const context = {};
const callback = () => {};

build.handler(event, context, callback).catch((error) => {
  console.error(error);
});
