#!/usr/bin/env node

import { handler } from "../functions/build/index.js";

const event = {};
const context = {};
const callback = (error) => {
  if (error) {
    console.error(`Build failed: ${error.message}`);
    process.exit(1);
  } else {
    console.log("Build succeeded");
    process.exit(0);
  }
};

await handler(event, context, callback).catch((error) => {
  console.error(error);
});
