#!/usr/bin/env sh

set -e

aws s3api create-bucket \
  --bucket frontpage-today-deployments \
  --region us-east-1 \
  --acl private

aws --region us-east-1 cloudformation package \
  --template template.yml \
  --output-template-file deploy-template.yml \
  --s3-bucket frontpage-today-deployments

aws --region us-east-1 cloudformation create-stack \
  --stack-name frontpage-today-prod \
  --template-body file://deploy-template.yml \
  --parameters file://config/prod.json \
  --capabilities CAPABILITY_IAM \
  --timeout-in-minutes 10
