#!/usr/bin/env sh

set -e

if [ -z "$1" ] ; then
  echo 'Expected config argument'
  exit 1
fi

if [ ! -f "config/$1.json" ]; then
  echo 'Config not found'
  exit 1
fi

aws --region us-east-1 cloudformation package \
  --template template.yml \
  --output-template-file deploy-template.yml \
  --s3-bucket "frontpage-$1-deployments" \
  --no-cli-pager

aws --region us-east-1 cloudformation deploy \
  --stack-name "frontpage-$1" \
  --template-file deploy-template.yml \
  --capabilities CAPABILITY_IAM \
  --no-cli-pager
